apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - releaseName: sealed-secrets
            repoURL: https://bitnami-labs.github.io/sealed-secrets
            targetRevision: 1.16.1
            namespace: kubeseal
          - releaseName: kube-prometheus-stack
            repoURL: https://prometheus-community.github.io/helm-charts
            targetRevision: 9.4.10
            namespace: prometheus
      - list:
          elements:
          - cluster: engineering-dev
            url: https://kubernetes.default.svc
          # - cluster: engineering-prod
          #   url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-{{releaseName}}'
    spec:
      project: default
      source:
        chart:  '{{releaseName}}'
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        helm:
          releaseName: '{{releaseName}}'
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}-{{namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true