apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/qxmips/applicationset.git
          revision: HEAD
          directories:
          - path: examples/myappsets/apps/*
      - list:
          elements:
          - cluster: engineering-dev
            url: https://kubernetes.default.svc
          - cluster: engineering-prod
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/qxmips/applicationset.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{url}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true