apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 9.4.10
    helm:
      releaseName: prometheus
      values: |
        foo: bar
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus